# -*- coding: utf-8 -*-
"""CNN1_FashionMNIST.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ORHNN_zsjoUs6wi_pTt3GZqDzIYullj_

Convolutional Neural Network on Fashion-MNIST
"""

import tensorflow as tf
import tensorflow_datasets as tfds
import matplotlib.pyplot as plt 
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Softmax, Flatten, Dropout, Conv2D, MaxPool2D
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import seaborn as sns

"""Load dataset from Tensorflow"""

fashion_mnist = tf.keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

"""Check Shape of Data"""

train_images.shape

"""View image of dataset"""

plt.figure()
plt.imshow(train_images[1], cmap= 'gray')
plt.colorbar()
plt.grid(False)
plt.show()

"""Resize dataset"""

train_images = train_images / 255.0

test_images = test_images / 255.0

"""View 25 images with label"""

plt.figure(figsize=(10,10))
for i in range(25):
    plt.subplot(5,5,i+1)
    plt.xticks([])
    plt.yticks([])
    plt.grid(False)
    plt.imshow(train_images[i], cmap=plt.cm.binary)
    plt.xlabel(class_names[train_labels[i]])
plt.show()

"""Create Model"""

model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(64, 2, input_shape=(28,28,1), padding='same'),
    tf.keras.layers.MaxPool2D(),
    tf.keras.layers.Dropout(0.20),
    tf.keras.layers.Conv2D(64, 2, padding='same'),
    tf.keras.layers.MaxPool2D(),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(10, activation='softmax')
])

"""Compile Model"""

model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

"""Summary model"""

model.summary()

"""Train the model"""

model.fit(train_images, train_labels, epochs=30)

"""Verify Accuracy"""

test_loss, test_acc = model.evaluate(test_images,  test_labels, verbose=2)

print('\nTest accuracy:', test_acc)

"""Model Predict"""

y_pred = model.predict(test_images)

"""Classification Report"""

y_pred = [np.argmax(arr) for arr in y_pred]
print(classification_report(test_labels, y_pred))

"""Confusion Matrix"""

cm = confusion_matrix(test_labels,y_pred)
cm

disp=ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=class_names)
fig, ax = plt.subplots(figsize=(10,10))
disp.plot(ax=ax);